image: docker:latest

services:
  - docker:dind

stages:
  - build

before_script:
  - apk add --no-cache yarn
  - yarn


octopus-openapi-json:
  stage: build
  script:
    yarn build

  artifacts:
    paths:
      - packages/octopus-oas/dist/openapi.json
