image: docker:latest

services:
  - docker:dind

stages:
  - build:all
  - build:specs-web
  - release
  - deploy

variables:
  DOCKER_DRIVER: overlay
  DOCS_WEB_IMAGE_TAG: "$CI_REGISTRY_IMAGE/specs-web:$CI_COMMIT_TAG"


build:
  stage: build:all
  script:
    - apk add --no-cache yarn
    - yarn install
    - yarn build

  artifacts:
    paths:
      - packages/octopus-oas/dist/openapi.json
      - packages/octopus-ts/dist
      - packages/specs-renderer/dist


build-specs-web:
  stage: build:specs-web
  script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
    - cp packages/octopus-oas/dist/openapi.json packages/specs-renderer/dist
    - cd packages/specs-renderer
    - docker build -t ${DOCS_WEB_IMAGE_TAG} .
    - docker push ${DOCS_WEB_IMAGE_TAG}
  only:
    - tags


release:
  stage: release
  script:
    - apk add --no-cache yarn
    - yarn install
    - echo "//registry.npmjs.org/:_authToken=${NPM_TOKEN}" > ~/.npmrc
    - yarn release
  only:
    - tags


bump-tools:
  stage: deploy
  image: registry.avcd.cz/backend/currywursterify-runner:latest
  variables:
    K8S_NAMESPACE: "tools"
    CI_PROJECT_NAME: "octopus-schema"
    IMAGE_TAG: "$CI_COMMIT_TAG"
  script: cd /app && ./chart.sh bump
  environment:
    name: tools
  only:
    - tags
