image: docker:latest

services:
  - docker:dind

stages:
  - build
  - release

before_script:
  - apk add --no-cache yarn
  - yarn


build-all:
  stage: build
  script:
    yarn build

  artifacts:
    paths:
      - packages/octopus-oas/dist/openapi.json


release:
  stage: release
  script:
    - yarn config set //registry.npmjs.org/:_authToken=${NPM_TOKEN}
    - yarn release
  only:
    - tags
