description: Common shadow properties.

type: object

properties:
  offset:
    $ref: '../schemas.yaml#/Vec2'

  blur:
    type: number
    format: float
    description: Blur value of the shadow.

  choke:
    type: number
    format: float
    description: Spread amount of the shadow contour.

  color:
    $ref: '../schemas.yaml#/Color'

required:
  - offset
  - blur
  - choke
  - color
