openapi: 3.0.3

info:
  title: Octopus Format OpenAPI specification
  version: 0.0.1
paths:
  /:
    get:
      responses:
        "200":
          description: OctopusComponent
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/OctopusComponent'
components:
  schemas:
    $ref: 'schemas/schemas.yaml'
